cart_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers ---------------------------------------
  up_left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_up_left_joint
    pid: {p: 5.0, i: 20, d: 0.0, i_clamp: 100.0}
  up_right_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_up_right_joint
    pid: {p: 5.0, i: 20, d: 0.0, i_clamp: 100.0}

  down_left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_down_left_joint
    pid: {p: 5.0, i: 20, d: 0.0, i_clamp: 100.0}
  down_right_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_down_right_joint
    pid: {p: 5.0, i: 20, d: 0.0, i_clamp: 100.0}